title: "Alissa Tran"
description: "Hi, I'm Alissa Tran. Welcome to my data portfolio.<br>I am a graduate of Master of Data Science and dream to become a Data Scientist who applies Data and AI to real-world problems."

theme: jekyll-theme-cayman

header_pages:
  - about.md
  - projects.md
  - contact.md
